In [1]:
#install with
#!pip install numpy
import numpy as np

In [7]:
grades = np.array([12,25,313,358])
print(grades.dtype)

int32


In [5]:
grades.mean()

177.0

In [6]:
print(type(grades))

<class 'numpy.ndarray'>


In [9]:
#creating an array
a = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

In [10]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
temp = np.array([
       [23,23,56,56,96],
       [45,34,45,55,56],
       [45,69,12,54,12]])

In [68]:
print(temp)

[[23 23 56 56 96]
 [45 34 45 55 56]
 [45 69 12 54 12]]


In [71]:
np.swapaxes(temp,1,1)

array([[23, 23, 56, 56, 96],
       [45, 34, 45, 55, 56],
       [45, 69, 12, 54, 12]])

In [75]:
#getting the max item from the array
print(np.max(temp))
#gives the max item by comparing each column
print(np.max(temp,axis = 0))
#gives out max item by comparing each row
print(np.max(temp,axis = 1))

96
[45 69 56 56 96]
[96 56 69]


In [32]:
# 3 rows and 2 columns
d = np.zeros((3,2))

In [34]:
print(d)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [40]:
b = np.arange(6)#a range

In [42]:
b.reshape(2,3)#reshape into 2 rows and 3 columns

array([[0, 1, 2],
       [3, 4, 5]])

In [123]:
A = np.arange(30).reshape(5,1,6)#reshape into 5 rows and 6 columns

In [132]:
print(A)
print(A.T)#transposed array can also use transpose()

[[[ 0  1  2  3  4  5]]

 [[ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]]

 [[18 19 20 21 22 23]]

 [[24 25 26 27 28 29]]]
[[[ 0  6 12 18 24]]

 [[ 1  7 13 19 25]]

 [[ 2  8 14 20 26]]

 [[ 3  9 15 21 27]]

 [[ 4 10 16 22 28]]

 [[ 5 11 17 23 29]]]


In [90]:
B = np.arange(40).reshape(1,5,8)

In [96]:
print(B.sum())

780


In [107]:
#mask returns a boolean value here we are getting true where we find the numbers which can be divided by 4 and returning True
mask = B % 4 == 0

In [108]:
mask

array([[[ True, False, False, False,  True, False, False, False],
        [ True, False, False, False,  True, False, False, False],
        [ True, False, False, False,  True, False, False, False],
        [ True, False, False, False,  True, False, False, False],
        [ True, False, False, False,  True, False, False, False]]])

In [109]:
#getting the numbers which are masked
B[mask]

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [118]:
#np.linespace is similar to np.arrange
#start(by defualt = 0,stop),interval
print(np.linspace(3,5,20,dtype = int))#generates numbers from 3 to 5
print(np.linspace(3,5,20))#if we dont specify dtype it generates float

[3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 5]
[3.         3.10526316 3.21052632 3.31578947 3.42105263 3.52631579
 3.63157895 3.73684211 3.84210526 3.94736842 4.05263158 4.15789474
 4.26315789 4.36842105 4.47368421 4.57894737 4.68421053 4.78947368
 4.89473684 5.        ]


In [133]:
#use -1 to automatically shape the array size (NOTE- one dimension has to be given)
y = print(np.arange(50).reshape(-1,10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [137]:
#sorting the array
np.sort(B)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39]]])

In [139]:
h = np.array([
       [4, 8],
       [6, 1]
    ])
g = np.array([
        [3, 5],
        [7, 2],
    ])

In [140]:
#vertical stacking
#the array dimensions must be same
np.vstack((h,g))

array([[4, 8],
       [6, 1],
       [3, 5],
       [7, 2]])

In [141]:
#horizontal stacking
np.hstack((h,g))

array([[4, 8, 3, 5],
       [6, 1, 7, 2]])

In [147]:
#this is a called as structured array this is more likely to used with csv files and other types of formats
data = np.array([
    ("KP", 56, 6000),
        ("Wells", 42, 20000),
      ("MG", 32, 10000),
        ("ROger", 56, 90000),
    ], dtype=[("name", str, 10), ("age", int),("Salary",int )])

In [148]:
data["age"]

array([56, 42, 32, 56])

In [149]:
data["Salary"]

array([ 6000, 20000, 10000, 90000])

In [151]:
data["name"]

array(['KP', 'Wells', 'MG', 'ROger'], dtype='<U10')

In [153]:
data[2]

('MG', 32, 10000)

In [155]:
#sorting the data in the array 
np.sort(data[data["Salary"] > 2000], order="name")

array([('KP', 56,  6000), ('MG', 32, 10000), ('ROger', 56, 90000),
       ('Wells', 42, 20000)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('Salary', '<i4')])